:concurrency: 5
:queues:
  - default
  - mailers
  - image_processing
  - notifications

:schedule:
  cleanup_expired_matches:
    cron: '0 2 * * *' # Daily at 2 AM
    class: 'CleanupExpiredMatchesJob'

