local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Cloudinary - Free tier: 25GB storage, 25GB bandwidth/month
# Sign up at https://cloudinary.com/users/register/free
cloudinary:
  service: Cloudinary
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

